#!/usr/bin/python

"""
Dictionary that contains the keywords required to categorize each transaction
into its corresponding category/subcategory.
"""
keywords = {
 'Comidas/Bar':                 ['OTELLI',
                                 'de Ruif',
                                 'BELVERDERE',
                                 'Cheve',
                                 'de Kurk',
                                 'The score',
                                 'Kiosk Tijd',
                                 'De Ark',
                                 'Bar',
                                 'Nastasta',
                                 'bar',
                                 'GALL',
                                 'Einstein'],
 'Comidas/Cenas':               ['EAZIE',
                                 '2DQ302',
                                 'NEW YORK PIZZA',
                                 'Ciao',
                                 'TAKEAWAY COM',
                                 'Pizza',
                                 'Kapsalon',
                                 'piza',
                                 'pizza',
                                 'MARMOTEL',
                                 'BURGERZ',
                                 'Burger',
                                 'Burgerz',
                                 'Burguerz',
                                 'Sport Center',
                                 'Sports center',
                                 'Lunchkiosk',
                                 'nner',
                                 'Doner',
                                 'Cena',
                                 'cena',
                                 'Dinner',
                                 'dinner',
                                 'Annie\'s Terras',
                                 'BK 20760',
                                 'Eazy',
                                 'Hamburguesa'],
 'Comidas/Comidas':             ['Leo van Vliet',
                                 'DONER KING',
                                 'Chipknip',
                                 'WORLD OF DELIGHTS',
                                 'FEBO',
                                 'de Bakker Cater',
                                 'VAP Buitenhof',
                                 'THE LIBERTIJN',
                                 'HEADQUARTER',
                                 'Gasterij',
                                 'BK 6156',
                                 'KFC',
                                 'MCDONALD',
                                 'Mc Donald',
                                 'ANTALYA',
                                 'Indo to Go',
                                 'NOORI',
                                 'PLUS Bomenwijk',
                                 'Smakers',
                                 'Smullers',
                                 'VIENA PARC',
                                 'Il Tartufo',
                                 'Oriental Delft',
                                 'Sodexo',
                                 'Achternaam',
                                 'RIJWIELH',
                                 'Subway',
                                 'GM 620',
                                 'McDonald',
                                 'julias',
                                 'Calcotada',
                                 'MM Den Haag',
                                 'Cafe Zeta',
                                 'ASD CS BK'],
 'Comidas/Snack':               ['The Coffee Company',
                                 'Fresh Tea',
                                 'Muffin',
                                 'Sodexa',
                                 'Smullers',
                                 'KOBUS KUCH',
                                 'Cinnabon',
                                 'Coffee-star',
                                 'KEK DELFT',
                                 'DOUWE EGBERTS COFFEE',
                                 'brownie',
                                 'Hema',
                                 'Broodzaak'],
 'Compras/Electronica':         ['Piston 2',
                                 'deal extrene',
                                 'Chromecast',
                                 'BCC',
                                 'TV',
                                 'Media Markt'],
 'Compras/Ropa':                ['C&A',
                                 'H & M',
                                 'America Today',
                                 'PRIMARK',
                                 'PULL AND BEAR'],
 'Compras/Varias':              ['Bike',
                                 'Xenos',
                                 'HEMA',
                                 'BLOKKER',
                                 'Gamma',
                                 'IKEA',
                                 'Ikea',
                                 'SENSA AT HOME',
                                 'HUUS'],
 'Entretenimiento/Cine':        ['Cine',
                                 'Pathe'],
 'Entretenimiento/Concierto':   ['ASOT', 
                                 'King\'s day'],
 'Entretenimiento/Juegos':      ['Holland Indoor Karti',
                                 'Ice kart',
                                 'RTD Kiosk Tnl'],
 'Entretenimiento/Museo':       ['Rembrandt van Gogh',
                                 'museum'],
 'Entretenimiento/Musica':      [],
 'Escuela/Beca':                ['TECHNISCHE UNIVERSITEIT'],
 'Escuela/Otros':               ['TU DELFT DIENST'],
 'Prestamo/Prestamo':           [],
 'Salud/Gimnasio':              ['2DQ301',
                                 'Raquetas'],
 'Salud/Medicinas':             ['FARMACIA',
                                 'Apotheek'],
 'Servicios/Banco':             ['ABN AMRO Bank N.V.'],
 'Servicios/Celular':           ['Vodafone',
                                 'VODAFONE'],
 'Servicios/Lavanderia':        [],
 'Servicios/Paqueteria':        ['DHL'],
 'Servicios/Renta':             ['DUWO'],
 'Servicios/Seguro':            ['OOM'],
 'Transferencia/Transferencia': ['GEA',
                                 'STORTING'],
 'Transporte/Taxi':             ['Taxi'],
 'Transporte/Auto':             ['Gasolina',
                                 'Viaje'],
 'Transporte/Trenes':           ['NS-',
                                 'NS GROEP',
                                 'SBB',
                                 'GANZONI BAS',
                                 'ov-chipkaart',
                                 'OV-Chipkaart'],
 'Varios/Varios':               ['De Delftse Bedrijvendagen'],
 'Viajes/Avion':                ['Avion'],
 'Viveres/Super':               ['Kruidvat',
                                 'ALBERT HEIJN',
                                 'Jumbo',
                                 'jumbo',
                                 'Carne',
                                 'MIGROS',
                                 'Supermarkt',
                                 'Super',
                                 'AH op',
                                 'AH Station',
                                 'AH to go']
 }